version: "3.5"

networks:
  iasandbox_net:
    name: iasandbox_net

services:
  iasandbox_chroma:
    container_name: iasandbox_chroma
    image: chromadb/chroma
    restart: always
    volumes:
      - /var/iasandbox/chroma:/chroma/chroma
    networks:
      - iasandbox_net
    ports:
      - "7000:8000"

  iasandbox_ollama:
    container_name: iasandbox_ollama
    image: ollama/ollama
    restart: always
    volumes:
      - /var/iasandbox/ollama:/root/.ollama
    networks:
      - iasandbox_net
    ports:
      - "7001:11434"

  iasandbox_api:
    container_name: iasandbox_api
    image: iasandbox-api-image
    restart: always
    volumes:
      - /var/iasandbox/files:/var/iasandbox/files
    depends_on:
      - iasandbox_ollama
      - iasandbox_chroma
    environment:
      - API_PORT=5010
      - FILES_PATH=
      - CHROMADB_PATH=
      - OLLAMA_PATH=
      - OAIK=
    networks:
      - iasandbox_net
    ports:
      - "7010:5010"
